### ISSUE TITLE
WrapKey support

### ISSUE THREAD

**Issue by jhfeng** [opendnssec/SoftHSMv2#183]
I need CKM_AES_KEY_WRAP_PAD support, which version openssl is required?

it looks like only openssl 1.1.0 support EVP_aes_*_wrap_pad() which is called by softHSM. But 1.1.0 remove BN_init(), so softHSM configure fails.

Is there suggestion ?

**Comment by agrandville** [comment]
openssl 's wrap pad functions are only defined in the master branch and will be disclosed in release 1.1.0 on 28th April 2016

**Comment by jhfeng** [comment]
so that means CKM_AES_KEY_WRAP_PAD is not supported currently in softHSM. Right ?

**Comment by pspacek** [comment]
It is supported in SoftHSM and actually works on platforms with appropriate OpenSSL version. E.g. Fedora 23 and RHEL 7.2 ship OpenSSL with necessary support.

**Comment by jhfeng** [comment]
thanks Petr. I'm testing with ubuntu and I installed openssl 1.1.0.pre2.  EVP_aws_*_wrap_pad is supported in openssl now, but  when I run softHSM configure, it failed with cannot find BN_init(), because BN_init() is replaced by BN_new() in openssl 1.1.0.

So I'm wondering how softHSM works on Fedora 23 and RHEL7.2. Somehow softHSM configure has to be corrected to use BN_new().

**Comment by pspacek** [comment]
Fedora and RHEL backported the functionality into older OpenSSL, that is why we did not hit this issue.

Can you test SoftHSM on Ubuntu with the following patch?
~~~
diff --git a/m4/acx_openssl.m4 b/m4/acx_openssl.m4
index d42e131..684860d 100644
--- a/m4/acx_openssl.m4
+++ b/m4/acx_openssl.m4
@@ -23,7 +23,7 @@ AC_DEFUN([ACX_OPENSSL],[
        LIBS="$LIBS $OPENSSL_LIBS"
 
        AC_CHECK_HEADERS([openssl/ssl.h],,[AC_MSG_ERROR([Can't find OpenSSL headers])])
-       AC_CHECK_LIB(crypto, BN_init,,[AC_MSG_ERROR([Can't find OpenSSL library])])
+       AC_CHECK_LIB(crypto, BN_new,,[AC_MSG_ERROR([Can't find OpenSSL library])])
 
        AC_MSG_CHECKING([for OpenSSL version])
        CHECK_OPENSSL_VERSION=m4_format(0x%02x%02x%02x000L, $1, $2, $3)
~~~

**Comment by jhfeng** [comment]
with your patch, I can get pass previous error, but getting Key wrapping not supported error:
.....
....
checking for crypto backend... OpenSSL
checking what are the OpenSSL includes... -I/usr/local/openssl/include
checking what are the OpenSSL libs... -L/usr/local/openssl/lib -lcrypto
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for BN_new in -lcrypto... yes
checking for OpenSSL version... >= 1.0.0
checking OpenSSL EVP interface for AES key wrapping... RFC 3394 is not supported
checking OpenSSL EVP interface for AES key wrapping with pad... RFC 5649 is not supported
...
...


How to enable them ?

**Comment by jhfeng** [comment]
here's error in config.log:

configure:5746: checking OpenSSL EVP interface for AES key wrapping
configure:5775: gcc -o conftest -g -O2 -pedantic -Wall -Wextra  -I/usr/local/openssl/include  conftest.c  -ldl -L/usr/local/openssl/lib -lcrypto >&5
/usr/local/openssl/lib/libcrypto.a(async.o): In function `async_free_pool_internal':
async.c:(.text+0xe4): undefined reference to `pthread_setspecific'
async.c:(.text+0xf4): undefined reference to `pthread_getspecific'
async.c:(.text+0x104): undefined reference to `pthread_setspecific'
/usr/local/openssl/lib/libcrypto.a(async.o): In function `async_start_func':
async.c:(.text+0x13f): undefined reference to `pthread_getspecific'
async.c:(.text+0x16e): undefined reference to `pthread_getspecific'
/usr/local/openssl/lib/libcrypto.a(async.o): In function `ASYNC_pause_job':
async.c:(.text+0x1bc): undefined reference to `pthread_getspecific'
async.c:(.text+0x1cc): undefined reference to `pthread_getspecific'
async.c:(.text+0x1e1): undefined reference to `pthread_getspecific'
/usr/local/openssl/lib/libcrypto.a(async.o):async.c:(.text+0x207): more undefined references to `pthread_getspecific' follow
/usr/local/openssl/lib/libcrypto.a(async.o): In function `ASYNC_init_thread':
async.c:(.text+0x38c): undefined reference to `pthread_setspecific'
/usr/local/openssl/lib/libcrypto.a(async.o): In function `ASYNC_start_job':
async.c:(.text+0x514): undefined reference to `pthread_getspecific'
async.c:(.text+0x52f): undefined reference to `pthread_getspecific'
async.c:(.text+0x545): undefined reference to `pthread_getspecific'
async.c:(.text+0x55e): undefined reference to `pthread_getspecific'
async.c:(.text+0x57f): undefined reference to `pthread_getspecific'
/usr/local/openssl/lib/libcrypto.a(async.o):async.c:(.text+0x59e): more undefined references to `pthread_getspecific' follow
/usr/local/openssl/lib/libcrypto.a(async.o): In function `ASYNC_start_job':
async.c:(.text+0x8c9): undefined reference to `pthread_setspecific'
async.c:(.text+0x8e9): undefined reference to `pthread_getspecific'
async.c:(.text+0x904): undefined reference to `pthread_getspecific'
async.c:(.text+0x916): undefined reference to `pthread_getspecific'
async.c:(.text+0x949): undefined reference to `pthread_getspecific'
async.c:(.text+0x969): undefined reference to `pthread_getspecific'
/usr/local/openssl/lib/libcrypto.a(async.o):async.c:(.text+0x984): more undefined references to `pthread_getspecific' follow
/usr/local/openssl/lib/libcrypto.a(async_posix.o): In function `async_global_init':
async_posix.c:(.text+0xc): undefined reference to `pthread_key_create'
async_posix.c:(.text+0x1e): undefined reference to `pthread_key_create'
/usr/local/openssl/lib/libcrypto.a(async_posix.o): In function `async_local_init':
async_posix.c:(.text+0x3d): undefined reference to `pthread_setspecific'
async_posix.c:(.text+0x50): undefined reference to `pthread_setspecific'
/usr/local/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/usr/local/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x314): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3bb): undefined reference to `dlerror'
/usr/local/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x434): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x4f6): undefined reference to `dlerror'
/usr/local/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x559): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x5bb): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x5f0): undefined reference to `dlerror'
/usr/local/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x67f): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x6e1): undefined reference to `dlerror'
/usr/local/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x732): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
configure:5775: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "SoftHSM"
| #define PACKAGE_TARNAME "softhsm"
| #define PACKAGE_VERSION "2.0.0"
| #define PACKAGE_STRING "SoftHSM 2.0.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "softhsm"
| #define VERSION "2.0.0"
| #define HAVE_DLOPEN 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_PTHREAD_H 1
| #define HAVE_OPENSSL_SSL_H 1
| #define HAVE_LIBCRYPTO 1
| /* end confdefs.h.  */
|
|
|           #include <openssl/evp.h>
|           int main()
|           {
|               EVP_aes_128_wrap();
|               return 1;
|           }
|
|
configure:5785: result: RFC 3394 is not supported

**Comment by jhfeng** [comment]
now i'm getting another issue:
......
OSSLAES.cpp: In member function 'bool OSSLAES::wrapUnwrapKey(const SymmetricKey*, SymWrap::Type, const ByteString&, ByteString&, int) const':
OSSLAES.cpp:157:75: error: invalid application of 'sizeof' to incomplete type 'EVP_CIPHER_CTX {aka evp_cipher_ctx_st}'
  EVP_CIPHER_CTX* pWrapCTX = (EVP_CIPHER_CTX*) salloc(sizeof(EVP_CIPHER_CTX));

according to https://groups.google.com/forum/#!topic/mailing.openssl.dev/z8ECwPooOD8
this is another openssl enhance for "type opacity"

Looks like softHSM need some code changes eventually for working with openssl 1.1.0.

**Comment by pspacek** [comment]
Yes, some changes are needed. Could you test patch https://github.com/pspacek/SoftHSMv2/commit/8719ef2e53af43ab70c77a72e8126f63e52771e8 , please?

**Comment by jhfeng** [comment]
Petr, I don't see PR#. I'm very familiar with git. so what is the command to pull this patch and merge into my local master branch code ?

**Comment by jhfeng** [comment]
In file included from OSSLMD5.h:37:0,
                 from OSSLCryptoFactory.cpp:39:
OSSLEVPHashAlgorithm.h:62:13: error: field 'curCTX' has incomplete type
  EVP_MD_CTX curCTX;
             ^
In file included from OSSLAES.h:36:0,
                 from OSSLCryptoFactory.cpp:37:
OSSLEVPHashAlgorithm.h: In constructor 'OSSLEVPHashAlgorithm::OSSLEVPHashAlgorithm()':
OSSLEVPHashAlgorithm.h:45:20: error: 'curCTX' was not declared in this scope
   EVP_MD_CTX_init(&curCTX);
                    ^
/usr/local/openssl/include/openssl/evp.h:576:52: note: in definition of macro 'EVP_MD_CTX_init'
 # define EVP_MD_CTX_init(ctx)    EVP_MD_CTX_reset((ctx))
                                                    ^
In file included from OSSLHMAC.h:37:0,
                 from OSSLCryptoFactory.cpp:45:
OSSLEVPMacAlgorithm.h: At global scope:
OSSLEVPMacAlgorithm.h:73:11: error: field 'curCTX' has incomplete type
  HMAC_CTX curCTX;
           ^
OSSLEVPMacAlgorithm.h: In constructor 'OSSLEVPMacAlgorithm::OSSLEVPMacAlgorithm()':
OSSLEVPMacAlgorithm.h:48:18: error: 'curCTX' was not declared in this scope
   HMAC_CTX_init(&curCTX);
                  ^
OSSLEVPMacAlgorithm.h:48:24: error: 'HMAC_CTX_init' was not declared in this scope
   HMAC_CTX_init(&curCTX);
                        ^
OSSLCryptoFactory.cpp: In constructor 'OSSLCryptoFactory::OSSLCryptoFactory()':
OSSLCryptoFactory.cpp:127:2: warning: 'void CRYPTO_set_id_callback(long unsigned int (*)())' is deprecated (declared at /usr/local/openssl/include/openssl/crypto.h:426) [-Wdeprecated-declarations]
  CRYPTO_set_id_callback(id_callback);
  ^
OSSLCryptoFactory.cpp:127:36: warning: 'void CRYPTO_set_id_callback(long unsigned int (*)())' is deprecated (declared at /usr/local/openssl/include/openssl/crypto.h:426) [-Wdeprecated-declarations]
  CRYPTO_set_id_callback(id_callback);
                                    ^
OSSLCryptoFactory.cpp: In destructor 'virtual OSSLCryptoFactory::~OSSLCryptoFactory()':
OSSLCryptoFactory.cpp:222:2: warning: 'void ERR_remove_state(long unsigned int)' is deprecated (declared at /usr/local/openssl/include/openssl/err.h:356) [-Wdeprecated-declarations]
  ERR_remove_state(0);
  ^
OSSLCryptoFactory.cpp:222:20: warning: 'void ERR_remove_state(long unsigned int)' is deprecated (declared at /usr/local/openssl/include/openssl/err.h:356) [-Wdeprecated-declarations]
.....

looks like hmac_ctx_st and evp_md_ctx_st are also moved and hidden to different files:-(

**Comment by pspacek** [comment]
Oh yes, more changes will be needed. I do not have time to fix it right now, but if you try it following the approach from my patch, I will help you with testing on Fedora and patch review.

**Comment by jhfeng** [comment]
yes, I fixed MD, HMAC and RSA part code, and now compiler is happy.
I need enable ecc/GOST also, to verify if these are also affected.
I'll submit the changes later after I testing in my test env.

**Comment by jhfeng** [comment]
Petr,
I'm trying to submit the patch, but failed with error:

2.7.9]jeffs-mbp-3:SoftHSMv2 jhfeng$ git push
Username for 'https://github.com': jhfeng
Password for 'https://jhfeng@github.com':
remote: Permission to opendnssec/SoftHSMv2.git denied to jhfeng.
fatal: unable to access 'https://github.com/opendnssec/SoftHSMv2.git/': The requested URL returned error: 403

failed also using SSH

is opendnssec/SoftHSMv2.git wrong repo ?

**Comment by jhfeng** [comment]
Petr,
please review this commit. There is no fix for ECC part in this commit.
https://github.com/jhfeng/SoftHSMv2/commit/0a42fcca093ade2a79cbf929c329a234c09388fd

**Comment by pspacek** [comment]
Unfortunatelly it does not compile on my Fedora 23 system with openssl-1.0.2f-1.fc23.x86_64.

It would be good to make it working on OpenSSL 1.0 and 1.1 at the same time.

~~~
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../../../git/src/lib/crypto -I../../.. -I../../../../git/src/lib/crypto/../common -I../../../../git/src/lib/crypto/../cryptoki_compat -I../../../../git/src/lib/crypto/../data_mgr -I../../../../git/src/lib/crypto/.. -I/usr/local/include -g -O2 -Wall -Wextra -fvisibility=hidden -MT OSSLEVPHashAlgorithm.lo -MD -MP -MF .deps/OSSLEVPHashAlgorithm.Tpo -c ../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp  -fPIC -DPIC -o .libs/OSSLEVPHashAlgorithm.o
../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp: In member function ‘virtual bool OSSLEVPHashAlgorithm::hashInit()’:
../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp:45:26: error: ‘EVP_MD_CTX_new’ was not declared in this scope
  curCTX = EVP_MD_CTX_new();
                          ^
../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp:52:25: error: ‘EVP_MD_CTX_free’ was not declared in this scope
   EVP_MD_CTX_free(curCTX);
                         ^
../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp: In member function ‘virtual bool OSSLEVPHashAlgorithm::hashUpdate(const ByteString&)’:
../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp:80:25: error: ‘EVP_MD_CTX_free’ was not declared in this scope
   EVP_MD_CTX_free(curCTX);
                         ^
../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp: In member function ‘virtual bool OSSLEVPHashAlgorithm::hashFinal(ByteString&)’:
../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp:105:25: error: ‘EVP_MD_CTX_free’ was not declared in this scope
   EVP_MD_CTX_free(curCTX);
                         ^
../../../../git/src/lib/crypto/OSSLEVPHashAlgorithm.cpp:112:24: error: ‘EVP_MD_CTX_free’ was not declared in this scope
  EVP_MD_CTX_free(curCTX);
                        ^
Makefile:720: recipe for target 'OSSLEVPHashAlgorithm.lo' failed
~~~

**Comment by jhfeng** [comment]
yeap. we need ifdef on openssl version. will modify it later.

**Comment by bellgrim** [comment]
I have created a new issue for adding support for OpenSSL 1.1.0. Closing this issue.
